wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: huggingface
    huggingface_version: 4.9.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      - 11
      4: 3.9.5
      5: 0.10.33
      6: 4.9.0.dev0
      8:
      - 5
